### ISSUE TITLE
can't pretty print nested [][]T

### ISSUE THREAD

**Issue by df51d** [timfayz/pretty#2]
Zig ver: 0.12.0-dev.3533+e5d900268
Minimal reproduction:
```zig
try pretty.print(std.heap.page_allocator, [0][0]u8{}, .{});
```
Error:
```zig
src/pretty.zig:721:51: error: expected type '[]const u8', found '*const [0][0]u8'
                        try self.writeValueString(&val, c);
                                                  ^~~~
src/pretty.zig:721:51: note: pointer type child '[0]u8' cannot cast into pointer type child 'u8'
src/pretty.zig:501:47: note: parameter type declared here
        fn writeValueString(self: *Self, str: []const u8, comptime ctx: Ctx) !void {
                                              ^~~~~~~~~~
```

**Comment by timfayz** [comment]
Received. I'll come back to it when I reach my laptop.

**Comment by timfayz** [comment]
First, thanks for the first pull request. Essentially, you put the comptime in front of the if and that solved the problem. Here is your commit: 

```zig
.Array => {
                // String
                comptime if (opt.str_is_u8 and typeIsArrayString(T)) {
                     try self.writeValueString(&val, c);
                     return;
                };
```

However, this introduces another problem. This `comptime` forces the body to be also comptime known, which will make `self.something` impossible to evaluate (self will be inevitably a non const pointer, and so a runtime thing). The question is, however, why then the `[0][0]u8{}` was successfully printed? It is simply because originally, the condition was assumed to be runtime and zig was forced check this branch (body) for the subject of type mismatch. The error you posted above is the result of that search. After your change, this branch is discarded as the condition can be evaluated during comptime now and it is false for your input (but it doesn't mean that for some other input zig will be able to evaluate it in comptime again).

When I was writing this code, I also assumed that the condition is comptime because `opt` is comptime by definition and `typeIsArrayString(T)` _shoud have been_ comptime, as it just has a single `type` argument, which is inherently comptime. However, as it turns out, zig sees the function call and immediately assumes it's gonna be a runtime if otherwise not specified. In short, to quick-fix it more correctly, we need to put `comptime` only in front of this function (to localize comptime-ness within the condition):

```zig
.Array => {
                // String
                if (opt.str_is_u8 and comptime typeIsArrayString(T)) {
                     try self.writeValueString(&val, c);
                     return;
                }
```
Another thing that I do appreciate is the style change you made. You put the `return` right after the try, and got rid of the `else` for the next block, which I consistently did in other parts of the code. So thank you again!

**PS.** I'll do this small fix, update tests if necessary, commit and push. After, I'll close your pull request with the reference to that commit.
